title: Database Internals Meetups
description: Database Internals Meetup community content.
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - reading-lists/index.md
 
social_links:
  - title: Database Internals Chat
    icon: telegram
    url: "https://t.me/databaseinternalschat"
  - title: Database Internals Site Sources
    icon: github
    url: "https://github.com/tsafin/db-internals-pages"

hide_site_feed_link: true
excerpt_separator: <!--more-->
